java_library(name = 'hashtag_aggregator',
  dependencies = [
    pants('3rdparty:easymock'),
    pants('3rdparty:guava'),
    pants('3rdparty:junit'),
    pants('src/java/com/twitter/common/testing'),
    pants('src/java/com/twitter/hashtag_aggregator'),
  ],
  sources = rglobs('*.java'),
)
